python script.py --mode=INTER_LINEAR --factor=0.2 --input_path='./selfie.jpg' --output_path='./output/INTER_LINEAR_02.jpg'
python script.py --mode=INTER_LINEAR --factor=5 --input_path='./selfie.jpg' --output_path='./output/INTER_LINEAR_5.jpg'
python script.py --mode=INTER_LINEAR --factor=32 --input_path='./selfie.jpg' --output_path='./output/INTER_LINEAR_32.jpg'
python script.py --mode=INTER_CUBIC --factor=0.2 --input_path='./selfie.jpg' --output_path='./output/INTER_CUBIC_02.jpg'
python script.py --mode=INTER_CUBIC --factor=5 --input_path='./selfie.jpg' --output_path='./output/INTER_CUBIC_5.jpg'
python script.py --mode=INTER_CUBIC --factor=32 --input_path='./selfie.jpg' --output_path='./output/INTER_CUBIC_32.jpg'